services:
  db:
    image: mysql:5.7
    container_name: wp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  wordpress:
    build:
      context: ./build-images/wordpress
      dockerfile: Dockerfile
    container_name: wp_app
    depends_on:
      - db
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB}
    volumes:
      - ./wp:/var/www/html
    ports:
      - "8080:80"

  cli:
    build:
      context: ./build-images/cli
      dockerfile: Dockerfile
    container_name: wp_cli
    depends_on:
      - db
      - wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB}
    volumes:
      - ./wp:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["/bin/sh", "-c"]
    command: ["while true; do sleep 3600; done"]

volumes:
  db_data:
